---

jobs:
  include:
    - language: bash
      stage: build artifacts
      env:
        - DISTRO=debian
          RELEASE=sid
        - DISTRO=ubuntu
          RELEASE=bionic
      install:
        - sudo apt update
        - sudo apt install --assume-yes make debootstrap debian-archive-keyring ubuntu-keyring rsync
      script:
        - ls -lha /usr/share/debootstrap/scripts/
        - sudo bash build.sh "$(echo "${DISTRO}" |tr -d '[:space:]')" "$(echo "${RELEASE}" |tr -d '[:space:]')"
    - language: bash
      install:
        - sudo apt-get install --assume-yes shellcheck
      script:
        - find . -type f -name "*.sh" -exec shellcheck "{}" \;

