---
language: bash
stage: build artifacts
name: Build image for ${DISTRO}/${RELEASE}
env:
  - DISTRO=debian
    RELEASE=sid
  - DISTRO=ubuntu
    RELEASE=bionic
install:
  - sudo apt update
  - sudo apt install --assume-yes debootstrap make debian-archive-keyring ubuntu-keyring rsync
script:
  - sudo bash build.sh "${DISTRO}" "${RELEASE}"

