---
language: bash
stage: build artifacts
env:
  - DISTRO=debian
    RELEASE=sid
  - DISTRO=ubuntu
    RELEASE=bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install debian-archive-keyring
  - echo -e "Package: debootstrap\nPin: release o=Debian\nPin-Priority: 1000\n\nPackage: *\nPin: release o=Debian\nPin-Priority: 90" |sudo tee /etc/apt/preferences.d/limit-debian
  - echo 'deb http://deb.debian.org/debian sid main' |sudo tee /etc/apt/sources.list.d/debian.list
  - sudo apt-get update
install:
  - sudo apt update
  - sudo apt install --assume-yes debootstrap make debian-archive-keyring ubuntu-keyring rsync
script:
  - ls /usr/share/debootstrap/scripts/
  - sudo bash build.sh "${DISTRO}" "${RELEASE}"

