---
language: bash
env:
  - DISTRIBUTION: debian
    CODENAME: sid
  - DISTRIBUTION: ubuntu
    CODENAME: bionic

jobs:
  include:
    - language: bash
      stage: build
      install:
        - sudo apt update
        - sudo apt install --assume-yes make debootstrap debian-archive-keyring ubuntu-keyring rsync
      script:
        - sudo sh build.sh "${DISTRIBUTION}" "${CODENAME}"

    #
    # Lint shell scripts
    #
    - language: bash
      stage: lint
      install:
        - sudo apt-get install --assume-yes shellcheck
      script:
        - find . -type f -name "*.sh" -print0 |xargs -0 -n1 shellcheck --shell=sh

