---
language: bash
stage: build artifacts
name: Build image for ${DISTRO}/${RELEASE}
env:
  - TARGET=sid
  - TARGET=bullseye
  - TARGET=buster
  - TARGET=bionic
  - TARGET=eoan
install:
  - sudo apt update
  - sudo apt install --assume-yes debootstrap make debian-archive-keyring ubuntu-keyring rsync
script:
  - sudo make "${TARGET}"

