---
language: bash
stage: build artifacts
env:
  - DISTRO=debian
    RELEASE=sid
  - DISTRO=ubuntu
    RELEASE=bionic
before_install:
  - sudo apt-get update
  - sudo apt-get install debian-archive-keyring
  - gpg --no-default-keyring --keyring /usr/share/keyrings/debian-archive-keyring.gpg --list-keys
  - sudo cp build-config/pin-debian /etc/apt/preferences.d/
  - sudo cp build-config/debian.list /etc/apt/sources.list.d/
  - sudo apt-get update
install:
  - sudo apt update
  - sudo apt install --assume-yes debootstrap make debian-archive-keyring ubuntu-keyring rsync
script:
  - ls /usr/share/debootstrap/scripts/
  - sudo bash build.sh "${DISTRO}" "${RELEASE}"

