---
env:
  - DISTRO: debian
    RELEASE: sid
  - DISTRO: ubuntu
    RELEASE: bionic

jobs:
  include:
    - language: bash
      stage: build
      install:
        - sudo apt update
        - sudo apt install --assume-yes make debootstrap debian-archive-keyring ubuntu-keyring rsync
      script:
        - ls -lha /usr/share/debootstrap/scripts/
        - sudo bash build.sh "$(echo "${DISTRO}" |tr -d '[:space:]')" "$(echo "${RELEASE}" |tr -d '[:space:]')"

    #
    # Lint shell scripts
    #
    - language: bash
      stage: lint
      install:
        - sudo apt-get install --assume-yes shellcheck
      script:
        - find . -type f -name "*.sh" -print0 |xargs -0 -n1 shellcheck --shell=sh

